[package]
name = "software"
version = "0.1.0"
edition = "2024"

[dependencies]
serialport = "4.7.2"
regex = "1.11.1"
common = { path = "../common" }
heapless = "0.8.0"
rand = "0.9.2"
rand_chacha = "0.9.0"
log = "0.4.27"
pico-args = "0.5.0"
chrono = "0.4.41"
postcard = "1.1.3"
