[package]
name = "receiver"
version = "0.1.0"
edition = "2024"

[dependencies]
pico-args = "0.5.0"
wavers = "1.5.1"
log = {  version = "0.4.27", features = ["std"] }
env_logger = "0.11.8"
chrono = "0.4.41"
regex = "1.11.1"
rustfft = "6.4.0"
